title: "Presentations by Jonathan Baruch"
description: "Conference talk show notes and resources"
author: "Jonathan Baruch"
author_name: "Jonathan Baruch"
avatar_url: "https://avatars.githubusercontent.com/u/1123"
hero_background: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=1920"
url: "https://jbaru.ch"
baseurl: ""

# Jekyll configuration
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
encoding: utf-8
timezone: UTC

# Collections
collections:
  talks:
    output: true
    permalink: /talks/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "talks"
    values:
      layout: "talk"

# Build settings
# sass:
#   style: compressed

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO and social
twitter:
  username: jbaruchel
  card: summary

social:
  name: Jonathan Baruch
  links:
    - https://github.com/jbaruch
    - https://twitter.com/jbaruchel

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - test/
  - .bundle/
  - node_modules/
  - .git/
  - README.md
  - docs/

# Security - Note: safe mode strips iframes, so disabled for embed functionality
# safe: true